// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Article struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status Status `json:"status"`
}

type Status string

const (
	StatusPublished Status = "PUBLISHED"
	StatusDraft     Status = "DRAFT"
	StatusPrivate   Status = "PRIVATE"
)

var AllStatus = []Status{
	StatusPublished,
	StatusDraft,
	StatusPrivate,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusPublished, StatusDraft, StatusPrivate:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
